[build]
  command = "npm run build:editor"
  publish = "dist"

[build.environment]
  SITE_MODE = "editor"
  HOSTING_PROVIDER = "netlify"

[[redirects]]
  from = "/api/keystatic/*"
  to = "/api/keystatic-handler/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

